// What the data builder (build-data.mjs) is told: where each country's regions are in Natural Earth, which
// projection draws them, and the few facts about names that Natural Earth does not carry. Read by nothing
// but that script; the package itself ships the data it makes.
//
// The division configs are the ones a Japanese study app by the same author drew its country maps with: the same filters
// on Natural Earth's admin-1 file, the same codes and the same projections, so a map drawn here is the map
// drawn there. They are projections of the d3-geo family, used here at build time only (a dev dependency):
// the data they make is plain paths on a fixed canvas, and the package depends on nothing.
import { geoAlbers, geoConicConformal, geoConicEqualArea, geoConicEquidistant, geoTransverseMercator } from "d3-geo";

/** Where Natural Earth is read from: a release tag of its own repository, and the file's SHA-256 at that tag. */
export const NATURAL_EARTH = {
  version: "5.1.2",
  tag: "v5.1.2",
  repository: "https://github.com/nvkelso/natural-earth-vector",
  raw: "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson",
  /** The day these files were fetched, written here rather than read from a clock so that the data is made the same each time. */
  retrieved: "2026-10-01",
  files: {
    "ne_110m_admin_0_countries.geojson": "6866c877d39cba9c357620878839b336d569f8c662d3cfab4cb1dbe2d39c977f",
    "ne_10m_admin_0_countries.geojson": "239eec57ac17f100a11e2536cffc56752c318b50ae765b0918ff7aab4ce8f255",
    "ne_50m_admin_0_countries.geojson": "3e458fc036ad0a66411f2c1e6cac49c5d7bfb81cb1123bc513b22511a2b7fdeb",
    "ne_10m_admin_1_states_provinces.geojson": "22d0e3ad85eb3e27f17cabf8ba2d50e554fbc27a87796ff891d958185da62fb5",
  },
};

/*
 * Left off every map. Antarctica is a continent and not a country (drawn whole it is a band the width of the
 * map); the French Southern Lands are uninhabited islands off it; Northern Cyprus and Somaliland are not on
 * the maps a school uses.
 */
export const EXCLUDED = new Set(["AQ", "TF", "CYN", "SOL"]);

/*
 * How the names Natural Earth writes with kanji are read, in hiragana. A katakana name is its own reading (a
 * foreign country's name is already the phonetic spelling), so only these need writing down. Hand-written, and
 * not yet read by a native reader.
 */
export const KANJI_READINGS = {
  西サハラ: "にしさはら",
  アメリカ合衆国: "あめりかがっしゅうこく",
  コンゴ民主共和国: "こんごみんしゅきょうわこく",
  ドミニカ共和国: "どみにかきょうわこく",
  フォークランド諸島: "ふぉーくらんどしょとう",
  東ティモール: "ひがしてぃもーる",
  南アフリカ共和国: "みなみあふりかきょうわこく",
  マリ共和国: "まりきょうわこく",
  中央アフリカ共和国: "ちゅうおうあふりかきょうわこく",
  コンゴ共和国: "こんごきょうわこく",
  赤道ギニア: "せきどうぎにあ",
  アラブ首長国連邦: "あらぶしゅちょうこくれんぽう",
  タイ王国: "たいおうこく",
  朝鮮民主主義人民共和国: "ちょうせんみんしゅしゅぎじんみんきょうわこく",
  大韓民国: "だいかんみんこく",
  モンゴル国: "もんごるこく",
  ソロモン諸島: "そろもんしょとう",
  中華人民共和国: "ちゅうかじんみんきょうわこく",
  中華民国: "ちゅうかみんこく",
  日本: "にほん",
  北マケドニア: "きたまけどにあ",
  コソボ共和国: "こそぼきょうわこく",
  南スーダン: "みなみすーだん",
};

/*
 * The everyday short name a Japanese child learns for the countries an elementary school's atlas names, where it
 * is not the name Natural Earth writes (アメリカ, not アメリカ合衆国), and how a short name in kanji is read.
 */
export const SHORT_NAMES_JA = {
  CN: ["中国", "ちゅうごく"],
  KR: ["韓国", "かんこく"],
  KP: ["北朝鮮", "きたちょうせん"],
  TW: ["台湾", "たいわん"],
  TH: ["タイ"],
  MN: ["モンゴル"],
  US: ["アメリカ"],
  ZA: ["南アフリカ", "みなみあふりか"],
};

export const DIVISION_CONFIGS = [
  {
    code: "CA",
    countryName: "Canada",
    divisionTypeName: "Province / territory",
    divisionTypePlural: "Provinces and territories",
    width: 1000,
    height: 720,
    filter: (f) => f.properties.iso_a2 === "CA" || f.properties.admin === "Canada",
    codeFn: (f) => f.properties.postal || f.properties.iso_3166_2?.replace(/^CA-/, ""),
    projection: () => geoConicConformal().parallels([49, 77]).rotate([96, 0]),
    regionFn: (f) => f.properties.region || "Canada",
    divisionType: "province",
  },
  {
    code: "GB",
    countryName: "United Kingdom",
    divisionTypeName: "Administrative division",
    divisionTypePlural: "Administrative divisions",
    width: 1000,
    height: 1100,
    filter: (f) => f.properties.iso_a2 === "GB",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^GB-/, "") || f.properties.postal || f.properties.adm1_code,
    projection: () => geoTransverseMercator().rotate([2, -54]),
    regionFn: (f) => f.properties.geonunit || f.properties.region || "United Kingdom",
    divisionType: "district",
  },
  {
    code: "FR",
    countryName: "France",
    divisionTypeName: "Department",
    divisionTypePlural: "Departments",
    width: 1000,
    height: 950,
    filter: (f) => f.properties.iso_a2 === "FR" && f.properties.type_en === "Metropolitan department",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^FR-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^FR\./, ""),
    projection: () => geoConicConformal().parallels([44, 49]).rotate([-3, 0]),
    regionFn: (f) => f.properties.region || "Metropolitan France",
    divisionType: "department",
  },
  {
    code: "DE",
    countryName: "Germany",
    divisionTypeName: "State",
    divisionTypePlural: "States",
    width: 1000,
    height: 1100,
    filter: (f) => f.properties.iso_a2 === "DE",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^DE-/, "") || f.properties.postal,
    projection: () => geoConicConformal().parallels([48, 54]).rotate([-10.5, 0]),
    regionFn: (f) => f.properties.region || "Germany",
    divisionType: "state",
  },
  {
    code: "IT",
    countryName: "Italy",
    divisionTypeName: "Province",
    divisionTypePlural: "Provinces",
    width: 1000,
    height: 1150,
    filter: (f) => f.properties.iso_a2 === "IT",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^IT-/, "") || f.properties.code_hasc?.replace(/^IT\./, ""),
    projection: () => geoTransverseMercator().rotate([-12.5, -42]),
    regionFn: (f) => f.properties.region || "Italy",
    divisionType: "province",
  },
  {
    code: "ES",
    countryName: "Spain",
    divisionTypeName: "Province",
    divisionTypePlural: "Provinces",
    width: 1000,
    height: 850,
    filter: (f) => f.properties.iso_a2 === "ES",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^ES-/, "") || f.properties.code_hasc?.replace(/^ES\./, ""),
    projection: () => geoConicConformal().parallels([36, 43]).rotate([3.5, 0]),
    regionFn: (f) => f.properties.region || "Spain",
    divisionType: "province",
  },
  {
    code: "MX",
    countryName: "Mexico",
    divisionTypeName: "State",
    divisionTypePlural: "States",
    width: 1000,
    height: 650,
    filter: (f) => f.properties.iso_a2 === "MX" && Boolean(f.properties.name),
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^MX-/, "") || f.properties.postal,
    projection: () => geoConicConformal().parallels([17.5, 29.5]).rotate([102, 0]),
    regionFn: (f) => f.properties.region || "Mexico",
    divisionType: "state",
  },
  {
    code: "CN",
    countryName: "China",
    divisionTypeName: "Province / municipality",
    divisionTypePlural: "Provinces and municipalities",
    width: 1000,
    height: 750,
    filter: (f) => f.properties.iso_a2 === "CN" && f.properties.name !== "Paracel Islands",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^CN-/, "") || f.properties.postal,
    projection: () => geoAlbers().parallels([25, 47]).rotate([-105, 0]),
    regionFn: (f) => f.properties.region || "China",
    divisionType: "province",
  },
  {
    code: "KR",
    countryName: "South Korea",
    divisionTypeName: "Province / city",
    divisionTypePlural: "Provinces and cities",
    width: 1000,
    height: 1200,
    filter: (f) => f.properties.iso_a2 === "KR",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^KR-/, "") || f.properties.code_hasc?.replace(/^KR\./, ""),
    projection: () => geoTransverseMercator().rotate([-127.5, -36]),
    regionFn: (f) => f.properties.region || "South Korea",
    divisionType: "province",
  },
  {
    code: "AU",
    countryName: "Australia",
    divisionTypeName: "State / territory",
    divisionTypePlural: "States and territories",
    width: 1000,
    height: 800,
    filter: (f) => f.properties.iso_a2 === "AU" && ["State", "Territory"].includes(f.properties.type_en),
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^AU-/, "") || f.properties.postal,
    projection: () => geoConicEqualArea().parallels([-18, -36]).rotate([-134, 0]),
    regionFn: (f) => f.properties.region || "Australia",
    divisionType: "state",
  },
  {
    code: "BR",
    countryName: "Brazil",
    divisionTypeName: "State",
    divisionTypePlural: "States",
    width: 1000,
    height: 1000,
    filter: (f) => f.properties.iso_a2 === "BR",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^BR-/, "") || f.properties.postal,
    projection: () => geoConicEqualArea().parallels([-5, -25]).rotate([52, 0]),
    regionFn: (f) => f.properties.region || "Brazil",
    divisionType: "state",
  },
  {
    code: "VN",
    countryName: "Vietnam",
    divisionTypeName: "Province / municipality",
    divisionTypePlural: "Provinces and municipalities",
    width: 1000,
    height: 1300,
    filter: (f) => f.properties.iso_a2 === "VN",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^VN-/, "") || f.properties.code_hasc?.replace(/^VN\./, ""),
    projection: () => geoTransverseMercator().rotate([-106.5, -16]),
    regionFn: (f) => f.properties.region || "Vietnam",
    divisionType: "province",
  },
  {
    code: "TW",
    countryName: "Taiwan",
    divisionTypeName: "County / city",
    divisionTypePlural: "Counties and cities",
    width: 1000,
    height: 1400,
    filter: (f) => f.properties.iso_a2 === "TW",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^TW-/, "") || f.properties.code_hasc?.replace(/^TW\./, ""),
    projection: () => geoTransverseMercator().rotate([-121, -23.7]),
    regionFn: (f) => f.properties.region || "Taiwan",
    divisionType: "county",
  },
  {
    code: "PH",
    countryName: "Philippines",
    divisionTypeName: "Province",
    divisionTypePlural: "Provinces",
    width: 1000,
    height: 1400,
    filter: (f) => f.properties.iso_a2 === "PH" && f.properties.type_en === "Province",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^PH-/, "") || f.properties.code_hasc?.replace(/^PH\./, ""),
    projection: () => geoTransverseMercator().rotate([-122, -13]),
    regionFn: (f) => f.properties.region || "Philippines",
    divisionType: "province",
  },
  {
    code: "TH",
    countryName: "Thailand",
    divisionTypeName: "Province",
    divisionTypePlural: "Provinces",
    width: 1000,
    height: 1400,
    filter: (f) => f.properties.iso_a2 === "TH",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^TH-/, "") || f.properties.code_hasc?.replace(/^TH\./, ""),
    projection: () => geoTransverseMercator().rotate([-101, -15]),
    regionFn: (f) => f.properties.region || "Thailand",
    divisionType: "province",
  },
  {
    code: "MY",
    countryName: "Malaysia",
    divisionTypeName: "State / territory",
    divisionTypePlural: "States and federal territories",
    width: 1000,
    height: 500,
    filter: (f) => f.properties.iso_a2 === "MY",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^MY-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^MY\./, ""),
    projection: () => geoConicConformal().parallels([2.5, 6]).rotate([-109, 0]),
    regionFn: (f) => f.properties.region || "Malaysia",
    divisionType: "state",
  },
  {
    code: "NL",
    countryName: "Netherlands",
    divisionTypeName: "Province",
    divisionTypePlural: "Provinces",
    width: 1000,
    height: 1100,
    filter: (f) => f.properties.iso_a2 === "NL" && f.properties.type_en === "Province",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^NL-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^NL\./, ""),
    projection: () => geoTransverseMercator().rotate([-5.3, -52.2]),
    regionFn: (f) => f.properties.region || "Netherlands",
    divisionType: "province",
  },
  {
    code: "RU",
    countryName: "Russia",
    divisionTypeName: "Federal subject",
    divisionTypePlural: "Federal subjects",
    width: 1000,
    height: 600,
    filter: (f) => f.properties.iso_a2 === "RU",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^RU-/, "") || f.properties.code_hasc?.replace(/^RU\./, ""),
    projection: () => geoConicEquidistant().parallels([50, 70]).rotate([-100, 0]),
    regionFn: (f) => f.properties.region || "Russia",
    divisionType: "federal subject",
  },
  {
    code: "NZ",
    countryName: "New Zealand",
    divisionTypeName: "Region",
    divisionTypePlural: "Regions",
    width: 1000,
    height: 1300,
    filter: (f) =>
      (f.properties.iso_a2 === "NZ" || f.properties.adm0_a3 === "NZL") &&
      ["Regional Council", "Unitary Authority", "Special Island Authority"].includes(f.properties.type_en),
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^NZ-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^NZ\./, ""),
    projection: () => geoTransverseMercator().rotate([-173, -41]),
    regionFn: (f) => f.properties.region || "New Zealand",
    divisionType: "region",
  },
  {
    code: "CO",
    countryName: "Colombia",
    divisionTypeName: "Department",
    divisionTypePlural: "Departments",
    width: 1000,
    height: 1200,
    filter: (f) => f.properties.iso_a2 === "CO" && f.properties.name !== "San Andrés y Providencia" && Boolean(f.properties.name),
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^CO-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^CO\./, ""),
    projection: () => geoTransverseMercator().rotate([73, -4]),
    regionFn: (f) => f.properties.region || "Colombia",
    divisionType: "department",
  },
  {
    code: "AR",
    countryName: "Argentina",
    divisionTypeName: "Province",
    divisionTypePlural: "Provinces",
    width: 1000,
    height: 1400,
    filter: (f) => f.properties.iso_a2 === "AR",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^AR-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^AR\./, ""),
    projection: () => geoTransverseMercator().rotate([65, -38]),
    regionFn: (f) => f.properties.region || "Argentina",
    divisionType: "province",
  },
  {
    code: "IE",
    countryName: "Ireland",
    divisionTypeName: "County",
    divisionTypePlural: "Counties",
    width: 1000,
    height: 1100,
    filter: (f) => f.properties.iso_a2 === "IE",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^IE-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^IE\./, ""),
    projection: () => geoTransverseMercator().rotate([8, -53.5]),
    regionFn: (f) => f.properties.region || "Ireland",
    divisionType: "county",
  },
  {
    code: "CH",
    countryName: "Switzerland",
    divisionTypeName: "Canton",
    divisionTypePlural: "Cantons",
    width: 1000,
    height: 650,
    filter: (f) => f.properties.iso_a2 === "CH",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^CH-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^CH\./, ""),
    projection: () => geoConicConformal().parallels([46, 47.5]).rotate([-8.2, 0]),
    regionFn: (f) => f.properties.region || "Switzerland",
    divisionType: "canton",
  },
  {
    code: "AT",
    countryName: "Austria",
    divisionTypeName: "State",
    divisionTypePlural: "States",
    width: 1000,
    height: 600,
    filter: (f) => f.properties.iso_a2 === "AT",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^AT-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^AT\./, ""),
    projection: () => geoConicConformal().parallels([47, 49]).rotate([-13.5, 0]),
    regionFn: (f) => f.properties.region || "Austria",
    divisionType: "state",
  },
  {
    code: "BE",
    countryName: "Belgium",
    divisionTypeName: "Province",
    divisionTypePlural: "Provinces",
    width: 1000,
    height: 900,
    filter: (f) => f.properties.iso_a2 === "BE",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^BE-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^BE\./, ""),
    projection: () => geoTransverseMercator().rotate([-4.5, -50.5]),
    regionFn: (f) => f.properties.region || "Belgium",
    divisionType: "province",
  },
  {
    code: "PL",
    countryName: "Poland",
    divisionTypeName: "Voivodeship",
    divisionTypePlural: "Voivodeships",
    width: 1000,
    height: 900,
    filter: (f) => f.properties.iso_a2 === "PL",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^PL-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^PL\./, ""),
    projection: () => geoConicConformal().parallels([50, 54]).rotate([-19, 0]),
    regionFn: (f) => f.properties.region || "Poland",
    divisionType: "voivodeship",
  },
  {
    code: "SE",
    countryName: "Sweden",
    divisionTypeName: "County",
    divisionTypePlural: "Counties",
    width: 1000,
    height: 1400,
    filter: (f) => f.properties.iso_a2 === "SE",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^SE-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^SE\./, ""),
    projection: () => geoTransverseMercator().rotate([-15, -62]),
    regionFn: (f) => f.properties.region || "Sweden",
    divisionType: "county",
  },
  {
    code: "NO",
    countryName: "Norway",
    divisionTypeName: "County",
    divisionTypePlural: "Counties",
    width: 1000,
    height: 1400,
    filter: (f) => f.properties.iso_a2 === "NO",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^NO-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^NO\./, ""),
    projection: () => geoTransverseMercator().rotate([-15, -65]),
    regionFn: (f) => f.properties.region || "Norway",
    divisionType: "county",
  },
  {
    code: "CL",
    countryName: "Chile",
    divisionTypeName: "Region",
    divisionTypePlural: "Regions",
    width: 1000,
    height: 1600,
    filter: (f) => f.properties.iso_a2 === "CL",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^CL-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^CL\./, ""),
    projection: () => geoTransverseMercator().rotate([71, -38]),
    regionFn: (f) => f.properties.region || "Chile",
    divisionType: "region",
  },
  {
    code: "PE",
    countryName: "Peru",
    divisionTypeName: "Department",
    divisionTypePlural: "Departments",
    width: 1000,
    height: 1300,
    filter: (f) => f.properties.iso_a2 === "PE",
    codeFn: (f) => f.properties.iso_3166_2?.replace(/^PE-/, "") || f.properties.postal || f.properties.code_hasc?.replace(/^PE\./, ""),
    projection: () => geoTransverseMercator().rotate([75, -9]),
    regionFn: (f) => f.properties.region || "Peru",
    divisionType: "department",
  },
];

