// The demo page's own words, in the two languages it speaks. Set as text, never as HTML. A word that is a function
// is filled in when it is said.
export const WORDS = {
  en: {
    pageApi: "API reference",
    pitch: "Japan's 47 prefectures, the world, its continents and 32 countries' regions, with their seas, lakes, rivers and mountains: a map to drag and zoom, quizzes to play and share, numbered callout sheets to print, and a map coloured from your own figures. The outlines are Natural Earth's, and every name is in English and Japanese.",
    name: "Chizu (地図) is Japanese for “map”, the everyday word, as in 世界地図, a map of the world.",
    nameLink: "About the name",
    map: "Map",
    part: "Part",
    mode: "Mode",
    modes: { explore: "Explore", quiz: "Quiz", callouts: "Callouts", colour: "Colour" },
    groupJapan: "Japan",
    japanPrefectures: "Japan: the 47 prefectures",
    groupWorld: "The world",
    groupContinents: "A continent",
    groupDivisions: "Regions of a country",
    groupCountry: "A country on its own",
    world: "The whole world",
    whole: "All of it",
    partContinents: "Continents",
    partSubregions: "Subregions",
    partGroups: "Its regions",
    regionsOf: (name, plural) => `${name}: ${plural.toLowerCase()}`,
    exploreTitle: "Names and places",
    filter: "Find",
    filterPlaceholder: "Part of a name",
    colCode: "Code",
    colIso: "ISO",
    colEnglish: "English",
    colJapanese: "日本語",
    colReading: "Reading",
    colGroup: "Part",
    nothingChosen: "Press a place on the map, or a row of the table below.",
    infoMap: (name, n, what) => `${name}: ${n} ${what}`,
    whatCountries: "countries",
    whatPlaces: "places",
    infoName: (en, ja) => `${en} · ${ja}`,
    group: "Part",
    isoCode: "ISO 3166-2",
    touches: "Touches",
    noNeighbours: "Touches no other place on this map.",
    centre: (lat, lon) => `Centre at ${lat} ${lon}`,
    north: "N",
    south: "S",
    east: "E",
    west: "W",
    download: "Download",
    downloadMap: "The map as you see it",
    downloadList: "The list of places",
    quizTitle: "Quiz",
    style: "Question",
    styles: { choose: "Pick a name", type: "Type the name", kana: "Type the reading", find: "Find it on the map", water: "Find the water" },
    questionWater: (name, kind) => `Where is ${name} (${kind})? Press it on the map.`,
    waterNeeds: "This map has too few seas, lakes and rivers for a round: choose the world, Japan, or a large country.",
    features: "Features",
    featureModes: { off: "Off", water: "Water", capitals: "Capitals", all: "Everything" },
    featuresTitle: "Seas, lakes, rivers and mountains",
    featureFind: "Find",
    featureFindPlaceholder: "A sea, a lake, a river…",
    featureCount: (shown, all) => (shown === all ? `${all} named on this map` : `${shown} of the ${all} named on this map`),
    featureNone: "Nothing on this map has a name of its own to find.",
    colKind: "Kind",
    kindLine: (kind) => kind,
    elevation: (metres) => `${metres.toLocaleString("en-US")} m`,
    rank: (n) => `Rank ${n}`,
    downloadFeatures: "The seas, lakes and rivers of this map",
    question: (what) => `Which ${what} is lit on the map?`,
    questionType: (what) => `Which ${what} is lit? Type its name, in English or Japanese.`,
    questionKana: (name) => `How is ${name} read? Type it in kana.`,
    questionFind: (name) => `Where is ${name}? Press it on the map.`,
    whatCountry: "country",
    whatRegion: "place",
    choices: "The choices",
    answer: "Your answer",
    answerPlaceholder: "Type here",
    answerKanaPlaceholder: "ひらがな or カタカナ",
    check: "Check",
    skip: "Show me",
    next: "Next question",
    right: "Right! ",
    wrong: (name) => `Not quite: it is ${name}.`,
    shown: (name) => `It is ${name}.`,
    youSaid: (said) => ` You said ${said}.`,
    kanaNeeds: "This map has too few names written in kanji to ask readings: choose Japan's prefectures, or the world.",
    quizNeeds: "The quiz needs a map with several places on it: choose the world, a continent, or the regions of a country.",
    round: (n, of) => `Question ${n} of ${of}`,
    score: (right, asked) => `${right} of ${asked}`,
    streak: (n) => `Streak ${n}`,
    best: (n) => `Best ${n}`,
    roundDone: (right, of, best) => `Round over: ${right} of ${of} right, best streak ${best}.`,
    roundTable: "This round",
    colQuestion: "No.",
    colPlace: "Place",
    colGiven: "Answer",
    colResult: "Result",
    resultRight: "Right",
    resultWrong: "Wrong",
    resultShown: "Shown",
    newRound: "New round",
    again: "Play this round again",
    share: "Share this round",
    shareText: "Anyone who opens this link gets the same questions in the same order:",
    copy: "Copy",
    copied: "Copied",
    calloutsTitle: "Numbered callouts in open water",
    calloutsText: "Each number sits in the sea, no two leader lines cross, and a line crosses as little other land as it can. Drag or zoom the map and they are placed again for what you see.",
    polish: "Tidy",
    numbering: "Numbers",
    off: "Off",
    on: "On",
    numberingOptions: { given: "As listed", "west-to-east": "West to east" },
    downloadSheet: "A sheet to print: the map and its numbered list",
    downloadLegend: "The numbered list",
    colourTitle: "Colour the map from your own figures",
    colourText: "Paste one place and one number to a line (a code, an ISO code or a name, then a comma or a tab, then the number). The places are shaded in five steps from the lowest to the highest.",
    colourBy: "Colour",
    colourModes: { figures: "By your figures", groups: "By part" },
    colourData: "Your figures",
    colourPlaceholder: "JP-13, 14047594\nOsaka, 8837685",
    colourExample: "Try an example",
    colourExampleNote: "The example counts how many places each one touches on this map, which the map itself knows.",
    colourCount: (matched, lines) => `${matched} of ${lines} lines matched a place.`,
    colourMissing: (lines) => `Not found: ${lines}`,
    colourBadNumber: (lines) => `No number: ${lines}`,
    colourEmpty: "Nothing to colour yet.",
    colourStep: (from, to) => `${from} to ${to}`,
    colValue: "Figure",
    colStep: "Step",
    downloadColoured: "The coloured map",
    downloadFigures: "The figures, matched to places",
    codeTitle: "Put this map on your page",
    codeText: "The code for the map as it is now: the map, the part, the colours and the numbers you see. Copy it into a page that has a <div id=\"map\">.",
    codeMount: "A map to drag and zoom",
    codeDraw: "A picture, as SVG text",
    moreTitle: "Using it",
    moreText: "Everything above is the package itself: the maps and their names, the framing, the drawing, the quizzes and the callout placer. Each line below is all it takes.",
    foot: "The outlines are Natural Earth's (public domain) and the names are kuni's (Unicode CLDR and Wikidata). Both are fetched from this page's own folder: nothing leaves your browser.",
  },
  ja: {
    pageApi: "API（英語）",
    pitch: "日本の47都道府県、世界、大陸、32か国の地方と、その海、湖、川、山。ドラッグして拡大縮小できる地図、遊んで共有できるクイズ、印刷できる番号つきの地図、自分の数値で色を塗った地図。輪郭はNatural Earthのもので、どのなまえも英語と日本語です。",
    name: "Chizu（ちず）は、日本語の「地図」のローマ字です。ふだんよく使うことばで、「世界地図」のように使います。",
    nameLink: "なまえについて（英語）",
    map: "地図",
    part: "範囲",
    mode: "モード",
    modes: { explore: "調べる", quiz: "クイズ", callouts: "番号", colour: "色分け" },
    groupJapan: "日本",
    japanPrefectures: "日本：47都道府県",
    groupWorld: "世界",
    groupContinents: "大陸",
    groupDivisions: "国の地方",
    groupCountry: "一つの国だけ",
    world: "世界全体",
    whole: "全体",
    partContinents: "大陸",
    partSubregions: "地域",
    partGroups: "地方",
    regionsOf: (name) => `${name}の地方`,
    exploreTitle: "なまえと場所",
    filter: "さがす",
    filterPlaceholder: "なまえの一部",
    colCode: "コード",
    colIso: "ISO",
    colEnglish: "English",
    colJapanese: "日本語",
    colReading: "読み",
    colGroup: "グループ",
    nothingChosen: "地図の場所か、下の表の行を押してください。",
    infoMap: (name, n, what) => `${name}：${n}${what}`,
    whatCountries: "か国",
    whatPlaces: "か所",
    infoName: (en, ja) => `${ja} · ${en}`,
    group: "グループ",
    isoCode: "ISO 3166-2",
    touches: "となり",
    noNeighbours: "この地図には、となりあう場所がありません。",
    centre: (lat, lon) => `中心は${lat} ${lon}`,
    north: "北緯",
    south: "南緯",
    east: "東経",
    west: "西経",
    download: "ダウンロード",
    downloadMap: "表示している地図",
    downloadList: "場所の一覧",
    quizTitle: "クイズ",
    style: "問題の種類",
    styles: { choose: "なまえを選ぶ", type: "なまえを入力する", kana: "読みを入力する", find: "地図でさがす", water: "海や川をさがす" },
    questionWater: (name, kind) => `${name}（${kind}）はどこでしょう？地図で押してください。`,
    waterNeeds: "この地図には海や湖や川が少ないので、問題を出せません。世界か日本か、大きな国を選んでください。",
    features: "重ね表示",
    featureModes: { off: "なし", water: "海と川", capitals: "首都", all: "すべて" },
    featuresTitle: "海、湖、川、山",
    featureFind: "さがす",
    featureFindPlaceholder: "海、湖、川のなまえ…",
    featureCount: (shown, all) => (shown === all ? `この地図に名前のあるもの${all}件` : `この地図に名前のあるもの${all}件のうち${shown}件`),
    featureNone: "この地図には、名前のあるものがありません。",
    colKind: "種類",
    kindLine: (kind) => kind,
    elevation: (metres) => `標高${metres.toLocaleString("ja-JP")}m`,
    rank: (n) => `ランク${n}`,
    downloadFeatures: "この地図の海、湖、川など",
    question: (what) => `地図で光っている${what}はどこでしょう？`,
    questionType: (what) => `光っている${what}はどこでしょう？なまえを英語か日本語で入力してください。`,
    questionKana: (name) => `「${name}」は何と読むでしょう？かなで入力してください。`,
    questionFind: (name) => `${name}はどこでしょう？地図で押してください。`,
    whatCountry: "国",
    whatRegion: "場所",
    choices: "選択肢",
    answer: "答え",
    answerPlaceholder: "ここに入力",
    answerKanaPlaceholder: "ひらがなかカタカナ",
    check: "答える",
    skip: "答えを見る",
    next: "つぎの問題",
    right: "正解です！ ",
    wrong: (name) => `ざんねん。答えは${name}です。`,
    shown: (name) => `答えは${name}です。`,
    youSaid: (said) => `（「${said}」と答えました）`,
    kanaNeeds: "この地図には漢字のなまえが少ないので、読みの問題は出せません。日本の都道府県か世界を選んでください。",
    quizNeeds: "クイズには、場所がいくつもある地図が必要です。世界か、大陸か、国の地方を選んでください。",
    round: (n, of) => `${of}問中${n}問目`,
    score: (right, asked) => `${asked}問中${right}問`,
    streak: (n) => `${n}問連続`,
    best: (n) => `最高${n}問連続`,
    roundDone: (right, of, best) => `おしまい：${of}問中${right}問正解、最高${best}問連続。`,
    roundTable: "今回の結果",
    colQuestion: "番号",
    colPlace: "場所",
    colGiven: "答え",
    colResult: "結果",
    resultRight: "正解",
    resultWrong: "不正解",
    resultShown: "答えを見た",
    newRound: "新しい問題で遊ぶ",
    again: "同じ問題でもう一度",
    share: "この問題を共有",
    shareText: "このリンクを開くと、だれでも同じ問題が同じ順で出ます：",
    copy: "コピー",
    copied: "コピーしました",
    calloutsTitle: "海の上の番号つき目印",
    calloutsText: "番号は海の上に置かれ、引き出し線は交差せず、他の陸地をなるべく横切りません。地図を動かしたり拡大したりすると、見えている範囲に合わせて置きなおします。",
    polish: "仕上げ",
    numbering: "番号",
    off: "なし",
    on: "あり",
    numberingOptions: { given: "一覧の順", "west-to-east": "西から東" },
    downloadSheet: "印刷用：地図と番号の一覧",
    downloadLegend: "番号の一覧",
    colourTitle: "自分の数値で地図に色を塗る",
    colourText: "1行に、場所と数値を一つずつ貼りつけてください。場所はコード、ISOコード、なまえのどれでもよく、数値とはカンマかタブで区切ります。数値の小さいほうから大きいほうへ、5段階で色がつきます。",
    colourBy: "塗り方",
    colourModes: { figures: "数値で", groups: "グループごとに" },
    colourData: "数値",
    colourPlaceholder: "JP-13, 14047594\n大阪府, 8837685",
    colourExample: "例を入れる",
    colourExampleNote: "例では、それぞれの場所がこの地図でいくつの場所ととなり合うかを数えています。地図そのものが知っている数です。",
    colourCount: (matched, lines) => `${lines}行のうち${matched}行が場所と一致しました。`,
    colourMissing: (lines) => `見つからない行：${lines}`,
    colourBadNumber: (lines) => `数値がない行：${lines}`,
    colourEmpty: "まだ塗るものがありません。",
    colourStep: (from, to) => `${from}〜${to}`,
    colValue: "数値",
    colStep: "段階",
    downloadColoured: "色を塗った地図",
    downloadFigures: "場所と対応させた数値",
    codeTitle: "この地図を自分のページに置く",
    codeText: "今の地図をそのまま描くコードです。地図、範囲、色、番号が入っています。<div id=\"map\">のあるページにコピーしてください。",
    codeMount: "ドラッグして拡大縮小できる地図",
    codeDraw: "SVGの文字列として描いた絵",
    moreTitle: "使い方",
    moreText: "上のすべては、このパッケージそのもの（地図となまえ、枠の取り方、描画、クイズ、目印の配置）で動いています。下の1行ずつが、それぞれに必要なコードのすべてです。",
    foot: "輪郭はNatural Earth（パブリックドメイン）、なまえはkuni（Unicode CLDRとWikidata）のもので、どちらもこのページと同じ場所から読み込みます。ブラウザーの外には何も送られません。",
  },
};
